### ISSUE TITLE
missing crypto import is failing test

### ISSUE THREAD

**Issue by monsieurBoutte** [w3cj/hono-node-deployment-examples#2]
[cross referencing this issue](https://github.com/w3cj/hono-open-api-starter/issues/13)

<img width="946" alt="Screenshot 2024-11-05 at 7 44 44 AM" src="https://github.com/user-attachments/assets/8dee35e1-1f98-4161-b3b4-21c17d03f932">

## the fix was adding an explicit import in the pino logger
<img width="646" alt="Screenshot 2024-11-07 at 8 23 06 AM" src="https://github.com/user-attachments/assets/604c61f0-ca87-47b7-a24a-ba172183dd6b">

**Comment by w3cj** [comment]
Updated example. Thanks!
